# Generated by Django 5.1.1 on 2024-10-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0005_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidad',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
