# Generated by Django 3.2 on 2024-10-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0008_entrevistador'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevistador',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='media/', verbose_name='Imagen'),
        ),
    ]
