# Generated by Django 4.1.5 on 2024-11-11 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0010_auto_20241031_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('ap1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ap1')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curriculums',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCurriculumExperiencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_Curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_experiencias', to='appportfolio.curriculum')),
                ('fk_Detalle_Experiencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_experiencias', to='appportfolio.experiencia')),
            ],
            options={
                'verbose_name': 'DetalleExperiencia',
                'verbose_name_plural': 'DetalleExperiencias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCurriculumEstudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_Curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_estudios', to='appportfolio.curriculum')),
                ('fk_Detalle_Estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_estudios', to='appportfolio.estudio')),
            ],
            options={
                'verbose_name': 'DetalleEstudio',
                'verbose_name_plural': 'DetalleEstudios',
                'ordering': ['id'],
            },
        ),
    ]
