# Generated by Django 4.1.5 on 2024-11-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0011_curriculum_detallecurriculumexperiencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='ap2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ap2'),
        ),
    ]
