# Generated by Django 4.1.5 on 2024-11-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0012_curriculum_ap2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Titulo')),
                ('contenido', models.TextField(blank=True, max_length=100, null=True, verbose_name='Contenido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagen', models.ImageField(blank=True, max_length=50, null=True, upload_to='media/', verbose_name='Imagen')),
            ],
        ),
    ]
